### ISSUE TITLE
Device locks when using serial + connected to computer

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-adafruit#632]
This program locks when connected to a computer
```
loops.forever(function () {
    light.graph(Math.randomRange(0, 10), 0)
})
```

**Comment by mmoskal** [comment]
Was it broken with WebUSB? Or was it non-functional before WebUSB?

**Comment by pelikhan** [comment]
It works https://makecode.adafruit.com/

**Comment by rachel-fenichel** [comment]
Bugreporting for a friend:
This is exposed in the "Loudness necklace" tutorial with this code that the tutorial says to write:
```
loops.forever(function () {
    light.graph(input.soundLevel(), 255)
})
```

"Froze within a second of starting with USB attached.  Disconnecting USB and running off of a battery caused the code to run fine without downloading it again.  Plugging back into USB immediately caused the lockup again.  

Hardware in use:

- Lenovo laptop T430 running Fedora 26 Linux
- Adafruit Circuit Playground Express (latest version)
Tutorials for Siren, Magic Wand, and Clap Lights all worked fine on this hardware setup with the USB cable both attached and disconnected.  (Disconnected running on lithium battery.)"

Possible priority bump since it's in a tutorial?

**Comment by pelikhan** [comment]
Could you ask if this was using the /beta app? @mmoskal

________________________________

**Comment by rachel-fenichel** [comment]
How do they know if they're using the beta?  Is the difference whether they were at https://makecode.adafruit.com/#editor vs https://makecode.adafruit.com/beta/#editor, or something else?

**Comment by pelikhan** [comment]
It's the only way to tell right now. Or go to gearwheel -> About and report the version number. Thanks!
![image](https://user-images.githubusercontent.com/4175913/36055766-af53b1a0-0db3-11e8-8fa2-4613b952741f.png)

**Comment by mmoskal** [comment]
It's possible this is broken under Linux also for HID not only WebUSB. If this is the case, we will need to apply a fix like the one in https://github.com/Microsoft/pxt-common-packages/pull/223

**Comment by rachel-fenichel** [comment]
Version info: 

![makecode_version](https://user-images.githubusercontent.com/13686399/36057047-a5cb67d0-0dbe-11e8-9a3e-bdd0471c7224.png)

**Comment by mmoskal** [comment]
So I guess we do need to avoid venting HID packets into space - apply https://github.com/Microsoft/pxt-common-packages/pull/223 uniformly also to HID. 

This would require changes in the Win 10 though, so that data logging continues to work - I guess the changes are only on the WebApp side, and similar to the ones we need for WebUSB.

**Comment by pelikhan** [comment]
@rachel-fenichel could you try https://makecode.adafruit.com/beta#editor (v0.1.13)?

**Comment by jafo408** [comment]
Hello there,

I am the "friend" on whose behalf Rachel reported this.  I just now signed up for my GitHub account at her request so I could comment directly.

I'm confirming the beta#editor mentioned above works for this code.  Screenshot of the version that works.  

![makecode_version_beta](https://user-images.githubusercontent.com/36319174/36057996-f0cebca2-0dcb-11e8-8095-6128952dd9ed.png)

Thank you for all your help on this.  Original bug identification goes to my 9 year old daughter.  :-)

**Comment by pelikhan** [comment]
You can thank your daughter for us! Is that her first reported/fixed bug? Well done!

________________________________

**Comment by jafo408** [comment]
I will definitely pass that along!  Yes, this was indeed her first bug find in someone else's code.  She's an active Scratch programmer at school and was excited when she could make a Magic Wand using the same method.  I told her earlier this evening that she had found a real bug and she got very excited. I'm sure your kind comments from the actual developers will be on proud display in her elementary school classroom Monday morning!

**Comment by abchatra** [comment]
This is fixed
