### ISSUE TITLE
grey'd text in tutorial

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#698]
https://forums.adafruit.com/viewtopic.php?f=48&t=134285

happens for me in latest firefox and also checked out chrome

![image](https://user-images.githubusercontent.com/1214161/38911543-1a5b8558-429e-11e8-968b-d989b5135877.png)

is it on purpose? :)

**Comment by pelikhan** [comment]
Oopsy. Looks like we have a feature interaction with the next iteration. All back to normal.

The grey code is the javascript that needs to be decompiled into blocks. We have a bug so that step never happens. If you press F12 in your browser and go to the console, you'll see a bunch of errors. All fixed up now.
